name: CRUD Tests

on:
  pull_request:
    paths:
      - 'src/**'
      - 'server/**'
      - '__tests__/**'
      - 'package.json'
      - 'jest.config.js'
  push:
    branches:
      - main
      - develop
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup test credentials
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > service-account-key.json
        cat > .env.test << EOF
        GOOGLE_DRIVE_FILE_ID=${{ secrets.TEST_FILE_ID }}
        NODE_ENV=test
        PORT=8081
        GOOGLE_APPLICATION_CREDENTIALS=./service-account-key.json
        EOF
        
    - name: Run linting
      run: npm run lint
      continue-on-error: true # Don't fail build on lint errors
      
    - name: Run unit tests
      run: npm test -- --testPathIgnorePatterns=e2e --coverage
      env:
        NODE_ENV: test
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          coverage/
          test-results/
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        flags: unittests
        fail_ci_if_error: false
        
    - name: Cleanup test data
      if: always()
      run: node scripts/cleanup-test-data.js
      continue-on-error: true
      
  e2e:
    runs-on: ubuntu-latest
    needs: test # Run after unit tests
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install chromium
        
    - name: Setup test credentials
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > service-account-key.json
        cat > .env.test << EOF
        GOOGLE_DRIVE_FILE_ID=${{ secrets.TEST_FILE_ID }}
        NODE_ENV=test
        PORT=8081
        GOOGLE_APPLICATION_CREDENTIALS=./service-account-key.json
        EOF
        
    - name: Build application
      run: npm run build
      
    - name: Start servers
      run: |
        npm run dev &
        node server.cjs &
        sleep 10 # Wait for servers to start
      env:
        NODE_ENV: test
        
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        NODE_ENV: test
        
    - name: Upload E2E test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: e2e-results
        path: |
          playwright-report/
          test-results/
          
    - name: Cleanup test data
      if: always()
      run: node scripts/cleanup-test-data.js
      continue-on-error: true
      
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run security audit
      run: npm audit --audit-level=high
      continue-on-error: true
      
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD