swagger: '2.0'
info:
  title: Risk Portal API Gateway
  description: API Gateway for Risk Portal Backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://risk-portal-backend-290017403746.us-central1.run.app
  path_translation: APPEND_PATH_TO_ADDRESS
paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: health
      responses:
        '200':
          description: Healthy
  /api/auth/login:
    post:
      summary: Login endpoint
      operationId: login
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Login successful
  /api/auth/register:
    post:
      summary: Register endpoint
      operationId: register
      responses:
        '200':
          description: Registration successful
  /api/auth/refresh:
    post:
      summary: Refresh token endpoint
      operationId: refresh
      responses:
        '200':
          description: Token refreshed
  /api/auth/logout:
    post:
      summary: Logout endpoint
      operationId: logout
      security:
        - api_key: []
      responses:
        '200':
          description: Logout successful
  /api/auth/me:
    get:
      summary: Get current user
      operationId: getCurrentUser
      security:
        - api_key: []
      responses:
        '200':
          description: User data
  /api/risks:
    get:
      summary: Get risks
      operationId: getRisks
      security:
        - api_key: []
      responses:
        '200':
          description: Risk list
  /api/controls:
    get:
      summary: Get controls
      operationId: getControls
      security:
        - api_key: []
      responses:
        '200':
          description: Control list
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header