steps:
  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/risk-portal/frontend:$COMMIT_SHA', '-f', 'Dockerfile.frontend', '.']
    id: 'build-frontend'
  
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/risk-portal/backend:$COMMIT_SHA', '-f', 'Dockerfile.backend', '.']
    id: 'build-backend'
  
  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/risk-portal/frontend:$COMMIT_SHA']
    waitFor: ['build-frontend']
  
  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/risk-portal/backend:$COMMIT_SHA']
    waitFor: ['build-backend']
  
  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'risk-portal-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/risk-portal/frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'
    id: 'deploy-frontend'
  
  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'risk-portal-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/risk-portal/backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '20'
      - '--set-secrets'
      - 'JWT_SECRET=jwt-secret:latest,SESSION_SECRET=session-secret:latest,GEMINI_API_KEY=gemini-api-key:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production,GCP_PROJECT_ID=dompe-dev-439304'
    id: 'deploy-backend'

# No substitutions needed anymore

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/risk-portal/frontend:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/risk-portal/backend:$COMMIT_SHA'